[package]
name = "beaver-code-repairer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[workspace]
#members = ["core", "scenes/*","src"]


[dependencies]
lazy_static = "1.4.0"
regex = "1.5.5"
yew = "0.19.3"
